JSON_MESSAGE_KEY = "message"

NOT_FOUND_ERROR_MESSAGE = "Not Found!"

CONTENT_TYPE_HEADER_KEY = "Content-Type"

JSON_CONTENT_TYPE_HEADER_VALUE = "application/json; charset=UTF-8"

INDEX_ROUTE = "/"

NOT_FOUND_ERROR_MESSAGE_JSON = { JSON_MESSAGE_KEY => NOT_FOUND_ERROR_MESSAGE }.to_json

NOTE_ID = 10
