#syntax=docker/dockerfile:experimental

FROM node:22-alpine

WORKDIR /src/app/

ENV SERVER_PORT=3006
ENV IN_MEMORY_DATABASE_HOST_NAME=host.docker.internal
ENV IN_MEMORY_DATABASE_HOST_PORT=3008

COPY ./tsconfig.json /src/app/tsconfig.json
COPY ./package.json /src/app/package.json
COPY ./package-lock.json /src/app/package-lock.json
COPY ./src/ /src/app/src/

RUN npm install --omit=dev

CMD npm run start

EXPOSE 3006
