# syntax=docker/dockerfile:1

FROM nimlang/nim

WORKDIR /usr/app/

ENV PORT=3002
ENV MESSAGE_QUEUE_SERVICE_URL=host.docker.internal:3004

COPY ./notes_api_service.nimble /usr/app/notes_api_service.nimble
COPY ./src/ /usr/app/src/

RUN nimble install

CMD nimble run

EXPOSE 3002
