class NoteConstants
  NOTE_TO_BE_CREATED_ID = 10

  NOTE_TO_BE_CREATED_TITLE = "Title"

  NOTE_TO_BE_CREATED_BODY = "Body"

  NOTE_TO_BE_CREATED_CREATED_AT_TIMESTAMP = 0

  NOTE_TO_BE_CREATED_UPDATED_AT_TIMESTAMP = 0

  NOTE_TO_BE_UPDATED_UPDATED_AT_TIMESTAMP = 1

  NUMBER_OF_NOTES_CREATED_BY_UNIQUE_USER = 2

  FIRST_NOTE_TO_BE_CREATED_ID = 0

  SECOND_NOTE_TO_BE_CREATED_ID = 1

  UPDATED_NOTE_TITLE = "New Title"

  UPDATED_NOTE_BODY = "New Body"

  NOTE_ROUTE = "/notes/"

  RESPONSE_MAP_MESSAGE_KEY = "message"

  NOTE_MAP_ID_KEY = "id"

  NOTE_MAP_TITLE_KEY = "title"

  NOTE_MAP_BODY_KEY = "body"

  NOTE_MAP_CREATED_AT_KEY = "createdAt"

  NOTE_MAP_UPDATED_AT_KEY = "updatedAt"

  NOTE_MAP_USER_ID_KEY = "userId"
end
