# syntax=docker/dockerfile:1

FROM ubuntu:24.04

RUN apt update && apt install redis-server redis-tools -y
RUN sysctl vm.overcommit_memory=1

CMD redis-server --port 3008 --protected-mode no

EXPOSE 3008