import json
from user_constants import USER_ID
from ../../domains/note/infrastructure/entities/note_entity import NoteEntity

const NOTE_ID_KEY* = "id"

const NOTE_TITLE_KEY* = "title"

const NOTE_BODY_KEY* = "body"

const NOTE_CREATED_AT_KEY* = "createdAt"

const NOTE_UPDATED_AT_KEY* = "updatedAt"

const NOTE_USER_ID_KEY* = "userId"

const NOT_EXISTING_NOTE_EXCEPTION_MESSAGE*: string = "Note Does Not Exist!"

const ALREADY_EXISTING_NOTE_EXCEPTION_MESSAGE*: string = "Note Already Exists!"

const NOTE_ID* = 1

const NOTE_TITLE* = "Title"

const NOTE_BODY* = "Body"

const NOTE_CREATED_AT* = 0

const NOTE_UPDATED_AT* = 0

const WRONG_NOTE_TITLE* = "Wrong Title"

let NOTE_DATA_TRANSFER_OBJECT_JSON* = %*{
  NOTE_ID_KEY: NOTE_ID,
  NOTE_TITLE_KEY: NOTE_TITLE,
  NOTE_BODY_KEY: NOTE_BODY,
  NOTE_CREATED_AT_KEY: NOTE_CREATED_AT,
  NOTE_UPDATED_AT_KEY: NOTE_UPDATED_AT,
  NOTE_USER_ID_KEY: USER_ID
}

let LIST_OF_NOTE_DATA_TRANSFER_OBJECT_JSON* = %*[{
  NOTE_ID_KEY: NOTE_ID,
  NOTE_TITLE_KEY: NOTE_TITLE,
  NOTE_BODY_KEY: NOTE_BODY,
  NOTE_CREATED_AT_KEY: NOTE_CREATED_AT,
  NOTE_UPDATED_AT_KEY: NOTE_UPDATED_AT,
  NOTE_USER_ID_KEY: USER_ID
}]

let NOTE_DATA_TRANSFER_OBJECT_JSON_WITH_WRONG_DATA* = %*{
  NOTE_ID_KEY: NOTE_ID,
  NOTE_TITLE_KEY: WRONG_NOTE_TITLE,
  NOTE_BODY_KEY: NOTE_BODY,
  NOTE_CREATED_AT_KEY: NOTE_CREATED_AT,
  NOTE_UPDATED_AT_KEY: NOTE_UPDATED_AT,
  NOTE_USER_ID_KEY: USER_ID
}

let NOTE_JSON* = %*{
  NOTE_TITLE_KEY: NOTE_TITLE,
  NOTE_BODY_KEY: NOTE_BODY,
}

let NOTE_JSON_WITH_WRONG_DATA* = %*{
  NOTE_TITLE_KEY: WRONG_NOTE_TITLE,
  NOTE_BODY_KEY: NOTE_BODY,
}

let NOTE_OBJECT* = NoteEntity(id: NOTE_ID, title: NOTE_TITLE, body: NOTE_BODY, createdAt: NOTE_CREATED_AT, updatedAt: NOTE_UPDATED_AT, userId: USER_ID)

let NOTE_OBJECT_WITH_WRONG_DATA* = NoteEntity(id: NOTE_ID, title: WRONG_NOTE_TITLE, body: NOTE_BODY, createdAt: NOTE_CREATED_AT, updatedAt: NOTE_UPDATED_AT, userId: USER_ID)

let MOST_NOTE_ID* = 999999999
