# syntax=docker/dockerfile:1

FROM gradle:latest

WORKDIR /usr/app/

ENV IN_MEMORY_SERVICE_URL=host.docker.internal:3006
ENV DATA_SOURCE_SERVICE_URL=host.docker.internal:3005

COPY ./settings.gradle /usr/app/settings.gradle
COPY ./gradlew /usr/app/gradlew
COPY ./build.gradle /usr/app/build.gradle
COPY ./src/ /usr/app/src/
COPY ./gradle /usr/app/gradle

CMD ./gradlew bootRun --args='--server.port=3004'

EXPOSE 3004
